[package]
name = "certonaut"
version = "0.1.0"
repository = "TODO"
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
aws-lc-rs = "1.11.1"
base64 = "0.22.1"
nom-rfc8288 = "0.2.3"
pem = "3.0.4"
rcgen = { version = "0.13.1", default-features = false, features = ["crypto", "pem", "aws_lc_rs", "x509-parser"] }
# TODO: rustls on Linux instead of OpenSSL?
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
time = { version = "0.3.36", features = ["serde", "formatting", "parsing"] }
# TODO: Narrow features
tokio = { version = "1.41.1", features = ["full"] }
tracing-subscriber = "0.3.18"
url = { version = "2.5.4", features = ["serde"] }
x509-parser = "0.16.0"

[build-dependencies]
toml = "0.8.19"

[dev-dependencies]
rstest = "0.23.0"
tempfile = "3.14.0"
