name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install deps
      run: |
        sudo apt-get install --yes --no-install-recommends clang libelf-dev zlib1g-dev linux-headers-$(uname -r)

    - name: Rust Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --verbose --locked --all-features
    
    - name: Run tests
      run: cargo test --verbose --locked --all-features
  
  integration-tests:
    name: "Integration Tests"
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get install --yes --no-install-recommends clang libelf-dev zlib1g-dev linux-headers-$(uname -r)
    - name: Download Pebble
      run: |
        git clone https://github.com/letsencrypt/pebble.git
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version-file: pebble/go.mod
    - name: Run Pebble
      run: |
        cd pebble
        go install ./...
        pebble -strict -config test/config/pebble-config.json -dnsserver :8053 &
        pebble-challtestsrv &
        cd ..

    - name: Rust Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run Integration Tests
      run: sudo -E env "PATH=$PATH" cargo test --locked --all-features -- --ignored
