name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install deps
      run: |
        sudo apt-get install --yes --no-install-recommends clang libelf-dev zlib1g-dev linux-headers-$(uname -r)
    
    - name: Build
      run: cargo build --verbose --locked --all-features
    
    - name: Run tests
      run: cargo test --verbose --locked --all-features
  
  integration-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt-get install --yes --no-install-recommends clang libelf-dev zlib1g-dev linux-headers-$(uname -r)
    - name: Download Pebble
      run: |
        git clone https://github.com/letsencrypt/pebble.git
        cd pebble
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version-file: go.mod
    - name: Run Pebble
      run: |
        go install ./...
        cd ..
        pebble -strict -config pebble/test/config/pebble-config.json -dnsserver :8053 &
        pebble-challtestsrv -config pebble/test/config/pebble-config.json &

    - name: Run full test suite
      run: sudo -E env "PATH=$PATH" cargo test --locked --all-features -- --ignored
